package types;

public enum Error {
	WRONG_INPUT,
	WRONG_COORDENATE,
    NO_PIECE_TO_MOVE,
    NO_YOUR_PIECE,
    WRONG_MOVEMENT,
    TARGET_NOT_EMPTY,
    DONT_EAT_PIECE,
    TOO_MUCH_ONE_MOVEMENT,
    NOT_MOVE_FORWARD,
    WRONG_DISTANCE,
    TOO_MUCH_ONE_JUMP
}